service: qwik-lambda-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  memorySize: 256
  timeout: 25
  stage: dev

functions:
  qwik:
    handler: server/entry_aws-lambda.qwikApp
    events:
      - httpApi: "*"
    environment:
      EXAMPLE: "my string"
      OPENAI_KEY: ${file(./.env.yml):OPENAI_KEY}
      HF_KEY: ${file(./.env.yml):HF_KEY}

custom:
  serverless-offline:
    httpPort: 4000
  customDomain:
    domainName: generatecoverimage.adhira.dev
    stage: ${self.provider.stage}
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: true
package:
  excludeDevDependencies: true
  patterns:
    - "!*"
    - "!*/**"
    - "server/**"
    - "dist/**"
    - "node_modules/**"
    - "node_modules/sharp/**"
    - "node_modules/color/**"
    - "node_modules/detect-libc/**"
    - "node_modules/semver/**"

plugins:
  - serverless-offline
  - serverless-domain-manager

